services:
  db:
    image: postgres:latest
    container_name: snsapp-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/pgdata" 
    volumes:
      - ./data:/pgdata  
